### ISSUE TITLE
Input types of lists or recursive products?

### ISSUE THREAD

**Issue by o1lo01ol1o** [con-kitty/categorifier-c#59]
It seems from the docstrings that it should be possible to have external types of lists of primitives and, perhaps harder, some sort of recursive struct.  Although thinking about this a little more, I assume you'd probably need the categorical treatment of recursion-schemes to handle this properly.  

How does kittyhawk deal with stateful functions of sequences or hashmaps (or catamorphisms more generally)?

In case I'm wrong and have overlooked something, my concrete issues are the following:

  In the case of lists, I'm unable to satisfy GArray's requirements.  Is there anything special that could make this work?  If not, I see there's some internal usage of finite vectors (`Vec`) internally, is there any reason that dynamically sized `Vector`s could not work?

In the case of recursive structs, I tried to include a naive tree in the sums example, but it looks like the HasRep instance fails for reasons I don't know. Are there any additional examples for hand writing such instances for more exotic types?

 For example, here's a tree added to sums example:

```haskell
data Tree a = Tree {tcons :: (Tree a, a, Tree a), tnil :: a}
  deriving (Eq, Ord, Generic, Functor)

deriveHasRep ''Tree

instance CGeneric (Tree (C Int32))

instance GArrays C (Tree (C Int32))

type instance TargetOb (Tree (C Int32)) = TargetOb (CG.Rep (Tree (C Int32)) ())

data Input = Input
  { iInt32 :: C Int32,
    iEnum :: KEnum C Pet,
    iTree :: Tree (C Int32)
  }
  deriving (Generic)
  ```
  
  
  This is a really cool project by the way!  It's great that you managed to productionize the concat work!

**Comment by zliu41** [comment]
@o1lo01ol1o there are two separate questions here:

- Can a function `A -> B` be categorified (i.e., turned into ``A `Categorifier.C.CExpr.Cat.Cat` B`` by the plugin), if `A` or `B` contains lists or `Tree`s?
- If so, can ``A `Categorifier.C.CExpr.Cat.Cat` B`` then be turned into C code?

The answer to the first question is yes, but to do so you can't derive `CGeneric` or `GArrays` instances, or define its `TargetOb` using `CG.Rep`. You'd need something like

```haskell
type instance TargetOb (Tree (C Int32)) = TargetOb (Categorifier.Client.Rep (Tree (C Int32)))
```

The answer to the second question is no, at least not in the current approach, because all generated C functions are like this:

```C
void simple_example (const bool input_bool[0] __attribute__((unused))
, const int8_t input_int8_t[3] __attribute__((unused))
, const int16_t input_int16_t[5] __attribute__((unused))
, const int32_t input_int32_t[1] __attribute__((unused))
, const int64_t input_int64_t[42] __attribute__((unused))
, const uint8_t input_uint8_t[100] __attribute__((unused))
, const uint16_t input_uint16_t[67] __attribute__((unused))
, const uint32_t input_uint32_t[55] __attribute__((unused))
, const uint64_t input_uint64_t[39] __attribute__((unused))
, const float input_float[10] __attribute__((unused))
, const double input_double[55] __attribute__((unused))
, bool output_bool[45] __attribute__((unused))
, int8_t output_int8_t[77] __attribute__((unused))
, int16_t output_int16_t[289] __attribute__((unused))
, int32_t output_int32_t[36] __attribute__((unused))
, int64_t output_int64_t[12] __attribute__((unused))
, uint8_t output_uint8_t[38] __attribute__((unused))
, uint16_t output_uint16_t[64] __attribute__((unused))
, uint32_t output_uint32_t[78] __attribute__((unused))
, uint64_t output_uint64_t[12] __attribute__((unused))
, float output_float[1] __attribute__((unused))
, double output_double[0] __attribute__((unused)));
```

which means we must know the sizes of the input and output statically - the Haskell function can't take or return lists of arbitrary sizes.

In fact currently even non-recursive sum types are not well supported outside of enum types and `Maybe`, although those would be much easier to support.

The good news is that you can still generate C code for `(g :: C -> B) . (f :: A -> C)` even if `C` contains lists or `Tree`s, as long as `A` and `B` don't.

**Comment by zliu41** [comment]
@o1lo01ol1o I added two examples, `recursive-types` and `recursive-types-2`. Hope they are helpful.

I make two corrections to my comment above:

> `type instance TargetOb (Tree (C Int32)) = TargetOb (Categorifier.Client.Rep (Tree (C Int32)))`

That doesn't work since it won't terminate. The examples I just added show the right approach.

> The good news is that you can still generate C code for (g :: C -> B) . (f :: A -> C) even if C contains lists or Trees, as long as A and B don't.

There's one more restriction, which is that lists or Trees can't appear in branches since they don't have `IfCat` instances (right now, non-recursive sum types can't either, although this is much easier to fix).

**Comment by o1lo01ol1o** [comment]
@zliu41 Thank you, that's quite helpful.  To be clear, the `IfCat` restriction on recursive types is not a fundemental issue, just  one that is not currently supported?

**Comment by zliu41** [comment]
> To be clear, the IfCat restriction on recursive types is not a fundemental issue, just one that is not currently supported?

I think it is likely a fundamental limitation of the current approach. To implement `IfCat` requires selecting one of two choices based on a `CExpr Bool`, which seems as hard as using recursive types as input and output - both require turning sum types into product types of known sizes. This can be done for non-recursive sum types, but probably not recursive ones.
